### ISSUE TITLE
Integration is not showing up in my sentry projects

### ISSUE THREAD

**Issue by danielbecker** [NDrive/sentry-mattermost#9]
Hi,

I used `pip install sentry_mattermost` to install the plugin and then did `SENTRY_CONF=/etc/sentry /www/sentry/bin/sentry upgrade` to update the sentry config.

However, the integration is not showing up in the list of integrations for my projects. What am I doing wrong?

**Comment by radoslavius** [comment]
You must use master from git with this command:
```
pip2.7 install -e git+https://github.com/NDrive/sentry-mattermost.git@master#egg=sentry-mattermost
```
but for sentry 9 not working. After small fix by me without python knowledge is working from our fork:
```
pip2.7 install -e git+https://github.com/pointcz/sentry-mattermost.git@master#egg=sentry-mattermost
```
![image](https://user-images.githubusercontent.com/3509024/54712068-aa1a6e00-4b4b-11e9-8636-9258a349293c.png)

**Comment by uhlhosting** [comment]
Hi @radoslavius, I have tested with our Sentry 9.1 and this did not worked. Are there any other updates or workarounds for this?

**Comment by radoslavius** [comment]
Hi @uhlhosting, After update to sentry 9.1.1 still works. Integration can be found in each project setting:
![image](https://user-images.githubusercontent.com/3509024/61520262-1a5bd200-aa0e-11e9-9bfb-52ff684874c0.png)
![image](https://user-images.githubusercontent.com/3509024/61520431-77f01e80-aa0e-11e9-97aa-6b7099c5c6c6.png)

**Comment by uhlhosting** [comment]
I receive a unknown plugin in legacy integrations unfortunatelly.

**Comment by radoslavius** [comment]
You can try another fork, for example from https://github.com/pointcz/sentry-mattermost

**Comment by avoulk** [comment]
I confirm this is not working on Sentry 9.1.2,  on_premise.
When configuring, it crashes with :

```python
Failed to load plugin 'mattermost':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 32, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/sentry_mattermost/plugin.py", line 29, in <module>
    from sentry.models import TagKey, TagValue
ImportError: cannot import name TagKey
```

**Comment by PXke** [comment]
Dear @avoulk

I do not know if it is something that is still of interest for you, but if it is could you give a go to: https://github.com/Biekos/sentry-mattermost ?

**Comment by jwillmer** [comment]
@PXke your fork is working on my on-premise installation. Could you activate the issue tab to collect feedback?

**Comment by avoulk** [comment]
Excellent, we will give it a try, many thanks!

**Comment by PXke** [comment]
@jwillmer Yes :) I am doing it tonight!
